frecon: Define get_monotonic_time_ms as static inline.
get_monotonic_time_ms is declared as inline and therefore
is not included in any object files.
This breaks linking in coverage builds.

Fixes following linker error with USE=coverage.
dbus.pie.o:dbus.c:__profd_get_monotonic_time_ms:
 error: undefined reference to 'get_monotonic_time_ms'

BUG=chromium:961510
TEST=USE=coverage emerge-amd64-generic frecon works.

Change-Id: Ib2c5d223d448d39f5a86f29862221e86056bf38b
Reviewed-on: https://chromium-review.googlesource.com/1604309
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
Reviewed-by: Dominik Behr <dbehr@chromium.org>